// Filtering numbers

SELECT PROVINCIA 
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE "Blister" > 20;


// Comparison Operators

SELECT PROVINCIA 
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE "Blister" <> 1;


// WHERE WITH STRINGS

SELECT PROVINCIA
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE PROVINCIA = 'BARCELONA';


// WHERE WITH COUNT 

SELECT COUNT(PROVINCIA)
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE PROVINCIA = 'BARCELONA';

// WHERE WITH COUNT  AND ALIAS 

SELECT COUNT(PROVINCIA) AS PROVINCIABARCELONA
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE PROVINCIA = 'BARCELONA';




// WHERE WITH DISTINCT

SELECT DISTINCT PROVINCIA
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE "Blister" > 1000


// WHERE WITH DISTINCT COUNT

SELECT COUNT(DISTINCT PROVINCIA)
FROM REPORTING.VENTAS_ZISD032B_GARZA
WHERE "Blister" > 1000





